name: Build VSCode Extension (multi-platform)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Node 22, weil VS Code/Electron 37.x auf Node 22 basiert (relevant fürs ABI der nativen Addons)
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Read package name/version
        id: meta
        run: |
          node -e "const fs=require('fs');const pkg=require('./package.json');fs.appendFileSync(process.env.GITHUB_OUTPUT,`name=${pkg.name}\nversion=${pkg.version}\npublisher=${pkg.publisher||''}\n`);"

      - name: Rebuild native addons for Electron (per target)
        run: npx electron-rebuild --force --version=37.6.0 --arch=${{ matrix.arch }}

      - name: Package VSIX (per target)
        run: npx vsce package --target ${{ matrix.platform }}-${{ matrix.arch }}

      # vsce erzeugt standardmäßig: <publisher>.<name>-<version>.vsix
      # Wir benennen es um auf: <name>-<platform>-<arch>-v<version>.vsix
      - name: Rename artifact to include name/platform/arch/version
        run: |
          node -e "const fs=require('fs');const pkg=require('./package.json');const plat='${{ matrix.platform }}';const arch='${{ matrix.arch }}';const old=(pkg.publisher?`${pkg.publisher}.`:'')+`${pkg.name}-${pkg.version}.vsix`;const neu=`${pkg.name}-${plat}-${arch}-v${pkg.version}.vsix`;if(!fs.existsSync(old)){console.error('VSIX not found:',old);process.exit(1);}fs.renameSync(old,neu);console.log('Renamed:',old,'->',neu);"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.meta.outputs.name }}-${{ matrix.platform }}-${{ matrix.arch }}-v${{ steps.meta.outputs.version }}
          path: "${{ steps.meta.outputs.name }}-${{ matrix.platform }}-${{ matrix.arch }}-v${{ steps.meta.outputs.version }}.vsix"