name: Build VSCode Extension (multi-platform)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Node 22, weil VS Code/Electron 37.x auf Node 22 basiert (relevant fürs ABI der nativen Addons)
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Rebuild native addons for Electron (per target)
        run: npx electron-rebuild --force --version=37.6.0 --arch=${{ matrix.arch }}

      - name: Package VSIX (per target)
        run: npx vsce package --target ${{ matrix.platform }}-${{ matrix.arch }}